name: mattermost-desktop
version: 4.2.0
summary: Open source, private cloud Slack-alternative
description: |
  Mattermost is secure workplace messaging from behind your firewall.

  - Discuss topics in private groups, one-to-one or team-wide
  - Easily share and view image files
  - Connect in-house systems with webhooks and Slack-compatible integrations

  To use this app, you need a URL for a Mattermost server.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

parts:
  gnome:
    plugin: nil
    override-pull: |
      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
      apt -y update
      apt -y upgrade

  libappindicator:
    plugin: nil
    after:
      - gnome
    stage-packages:
      - libappindicator3-1
    build-attributes:
      - no-system-libraries
    prime:
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdbusmenu*.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libappindicator*.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libindicator*.so*

  mattermost-desktop:
    plugin: dump
    source:
      - on amd64: https://releases.mattermost.com/desktop/$SNAPCRAFT_PROJECT_VERSION/mattermost-desktop-$SNAPCRAFT_PROJECT_VERSION-linux-amd64.deb
      - on i386: https://releases.mattermost.com/desktop/$SNAPCRAFT_PROJECT_VERSION/mattermost-desktop-$SNAPCRAFT_PROJECT_VERSION-linux-i386.deb
    source-type: deb
    # Correct path to icon.
    override-build: |
      snapcraftctl build
      # Correct the Icon path
      sed -i 's|Icon=mattermost-desktop|Icon=${SNAP}/usr/share/icons/hicolor/256x256/apps/mattermost-desktop.png|' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/mattermost-desktop.desktop
    after:
      - gnome
      - desktop-gnome-platform
      - libappindicator
    build-attributes:
      - no-system-libraries
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnspr4
      - libnss3
      - libxss1

apps:
  mattermost-desktop:
    command: bin/desktop-launch $SNAP/opt/Mattermost/mattermost-desktop
    desktop: usr/share/applications/mattermost-desktop.desktop
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to
      # ensure libappindicator has readable resources
      TMPDIR: $XDG_RUNTIME_DIR
      # Coerce XDG_CURRENT_DESKTOP to Unity so that App Indicators
      # are used and do not fall back to Notification Area applets
      # or disappear completely.
      XDG_CURRENT_DESKTOP: Unity
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
      - bluez
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - opengl
      - pulseaudio
      - removable-media
      - unity7
      - wayland
      - x11
