name: mattermost-desktop
version: 5.5.1
base: core22
summary: Open source, private cloud Slack-alternative
description: |
  Mattermost is secure workplace messaging from behind your firewall.

  - Discuss topics in private groups, one-to-one or team-wide
  - Easily share and view image files
  - Connect in-house systems with webhooks and Slack-compatible integrations

  To use this app, you need a URL for a Mattermost server.

grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  bsi-trigger: # A non-built part, only used to trigger builds in build.snapcraft.io on upstream changes
    plugin: nil
    source: https://github.com/mattermost/desktop.git

  mattermost-desktop:
    plugin: dump
    source: https://releases.mattermost.com/desktop/$SNAPCRAFT_PROJECT_VERSION/mattermost-desktop_$SNAPCRAFT_PROJECT_VERSION-1_$SNAPCRAFT_TARGET_ARCH.deb
    source-type: deb
    build-packages: [wget, ca-certificates]
    override-build: |
      craftctl default
      sed -i 's|Icon=mattermost-desktop|Icon=/usr/share/icons/hicolor/256x256/apps/mattermost-desktop.png|' ${CRAFT_PART_INSTALL}/usr/share/applications/mattermost-desktop.desktop
    prime:
      - -opt/Mattermost/chrome-sandbox
    stage-packages:
      - libnspr4
      - libnss3
      - libxss1
  cleanup:
    after: [mattermost-desktop]
    plugin: nil
    build-snaps: [gnome-42-2204]
    override-prime: |
      set -eux
      cd /snap/gnome-42-2204/current
      find . -type f,l -exec rm -f $CRAFT_PRIME/{} \;
  local-parts:
    plugin: dump
    source: snap/local
    source-type: local
    after: [cleanup]

apps:
  mattermost-desktop:
    extensions: [gnome]
    command-chain: [opt/Mattermost/fix-default-download-dir]
    command: opt/Mattermost/mattermost-desktop --no-sandbox --disable-seccomp-filter-sandbox
    desktop: usr/share/applications/mattermost-desktop.desktop
    autostart: mattermost-desktop.desktop
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to
      # ensure libappindicator has readable resources
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - shmem
      - gsettings
      - home
      - login-session-observe
      - network
      - network-bind
      - opengl
      - pulseaudio
      - audio-playback
      - audio-record
      - removable-media
      - screen-inhibit-control
      - unity7
      - camera

plugs:
  shmem:
    interface: shared-memory
    private: true
