name: mattermost-desktop
version: 4.6.2
base: core18
summary: Open source, private cloud Slack-alternative
description: |
  Mattermost is secure workplace messaging from behind your firewall.

  - Discuss topics in private groups, one-to-one or team-wide
  - Easily share and view image files
  - Connect in-house systems with webhooks and Slack-compatible integrations

  To use this app, you need a URL for a Mattermost server.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

parts:
  bsi-trigger: # A non-built part, only used to trigger builds in build.snapcraft.io on upstream changes
    plugin: nil
    source: https://github.com/mattermost/desktop.git

  libappindicator:
    plugin: nil
    stage-packages:
      - libappindicator3-1
    prime:
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdbusmenu*.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libappindicator*.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libindicator*.so*

  mattermost-desktop:
    after: [libappindicator]
    plugin: dump
    source:
      - on amd64: https://releases.mattermost.com/desktop/$SNAPCRAFT_PROJECT_VERSION/mattermost-desktop-$SNAPCRAFT_PROJECT_VERSION-linux-amd64.deb
      - on i386: https://releases.mattermost.com/desktop/$SNAPCRAFT_PROJECT_VERSION/mattermost-desktop-$SNAPCRAFT_PROJECT_VERSION-linux-i386.deb
    source-type: deb
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=mattermost-desktop|Icon=/usr/share/icons/hicolor/256x256/apps/mattermost-desktop\.png|' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/mattermost-desktop.desktop
    prime:
      - -opt/Mattermost/chrome-sandbox
    stage-packages:
      - libnspr4
      - libnss3
      - libxss1
  cleanup:
    after: [mattermost-desktop]
    plugin: nil
    build-snaps: [ gnome-3-28-1804 ]
    override-prime: |
        set -eux
        cd /snap/gnome-3-28-1804/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;

apps:
  mattermost-desktop:
    extensions: [gnome-3-28]
    command: opt/Mattermost/mattermost-desktop --no-sandbox
    desktop: usr/share/applications/mattermost-desktop.desktop
    autostart: mattermost-desktop.desktop
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to
      # ensure libappindicator has readable resources
      TMPDIR: $XDG_RUNTIME_DIR
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
      - browser-support
      - gsettings
      - home
      - login-session-observe
      - network
      - network-bind
      - opengl
      - pulseaudio
      - audio-playback
      - audio-record
      - removable-media
      - screen-inhibit-control
      - unity7
      - camera
