name: Release

on:
  # Run the workflow each time new commits are pushed to the candidate branch. 
  push:
    branches: [ "candidate" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  check-version:
    name: 🔍 Check if pre-release version
    runs-on: ubuntu-latest
    outputs:
      is-prerelease: ${{ steps.check.outputs.is-prerelease }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check version
        id: check
        run: |
          if awk '/^version:/ {print "Version:", $2; exit ($2 ~ /(rc|beta|alpha)/)}' snap/snapcraft.yaml; then
            echo "is-prerelease=false" >> $GITHUB_OUTPUT
            echo "This is a stable version"
          else
            echo "is-prerelease=true" >> $GITHUB_OUTPUT
            echo "This is a pre-release version"
          fi

  get-architectures:
    name: 🖥 Get snap architectures
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.get-architectures.outputs.architectures }}
      architectures-list: ${{ steps.get-architectures.outputs.architectures-list }}
    steps:
      - name: 🖥 Get snap architectures
        id: get-architectures
        uses: snapcrafters/ci/get-architectures@main

  release:
    name: 🚢 Release to latest/candidate
    needs: get-architectures
    runs-on: ubuntu-latest
    environment: "Candidate Branch"
    strategy:
      matrix:
        architecture: ${{ fromJSON(needs.get-architectures.outputs.architectures-list) }}
    steps:
      - name: 🚢 Release to latest/candidate
        uses: snapcrafters/ci/release-to-candidate@main
        with:
          architecture: ${{ matrix.architecture }}
          launchpad-token: ${{ secrets.LP_BUILD_SECRET }}
          repo-token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}
          store-token: ${{ secrets.SNAP_STORE_CANDIDATE }}
  
  call-for-testing:
    name: 📣 Create call for testing
    needs: [release, get-architectures, check-version]
    if: needs.check-version.outputs.is-prerelease == 'false'
    environment: "Candidate Branch"
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.issue.outputs.issue-number }}
    steps:
      - name: 📣 Create call for testing
        id: issue
        uses: snapcrafters/ci/call-for-testing@main
        with:
          architectures: ${{ needs.get-architectures.outputs.architectures }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
  screenshots:
    name: 📸 Gather screenshots
    needs: [call-for-testing, check-version]
    if: needs.check-version.outputs.is-prerelease == 'false'
    environment: "Candidate Branch"
    runs-on: ubuntu-latest
    steps:
      - name: 📸 Gather screenshots
        uses: snapcrafters/ci/get-screenshots@main
        with:
          issue-number: ${{ needs.call-for-testing.outputs.issue-number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          screenshots-token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}
