name: 🔄 Sync version with upstream

on:
  # Runs at 10:00 UTC every day
  schedule:
    - cron:  '0 10 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  sync-version:
    name: "Update snapcraft.yaml"
    environment: "Candidate Branch"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}
      - name: Fetch release version
        run: |
          VERSION=$(
            curl -sL https://api.github.com/repos/mattermost/desktop/releases | 
            jq .  | grep tag_name | grep -v beta | grep -v rc | head -n 1 | cut -d'"' -f4 | tr -d 'v'
          )
          sed -i 's/^\(version: \).*$/\1'"$VERSION"'/' snap/snapcraft.yaml
      - name: Check for modified files
        id: git-check
        run: |
          MODIFIED=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
          echo "modified=$MODIFIED" >> $GITHUB_OUTPUT
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Snapcrafters Bot'
          git config --global user.email 'merlijn.sebrechts+snapcrafters-bot@gmail.com'
          git commit -am "Automatic sync to latest release"
          git push
    outputs:
      modified: ${{ steps.git-check.outputs.modified }}
